#!/usr/bin/bash
#
act=$1
l=$2

if [ -z "$act" ]; then 
  cat ~/.doing/transitions | did
    is=`tail -n 1 ~/.doing/transitions 2> /dev/null | cut -f 1`
    [ -n "$is" ] && echo "Now doing $is"
  exit 0
fi

late=${l:=0}

acts=(`grep $act ~/.doing/acts`)

case "${#acts[@]}" in
  0) 
    echo "No matching activity in ~/.doing/acts"
    ;;
  1) 
    msg=`cat -`
    line="${acts[0]}\t`date --date "-$late min" --iso-8601=seconds`\t$msg"
    was=`tail -n 1 ~/.doing/transitions 2> /dev/null | cut -f 1`
    [ -n "$was" ] && echo "Was doing $was"
    echo -e $line
    echo -e $line >> ~/.doing/transitions
    ;;
  *)
    echo "Multiple matches in ~/.doing/acts: ${acts[@]}" 
    ;;
esac

